package handlers

import (
	"archive/zip"
	"bytes"
	"fmt"
	"io/fs"
	"net/http"
	"strconv"
	"strings"
	"time"

	"fishing-platform-backend/config"
	"fishing-platform-backend/models"
	"fishing-platform-backend/utils"
	"github.com/gin-gonic/gin"
)

var qrRelayScriptFS fs.FS

// RegisterQrRelayScriptFS wires the embedded scripts/qr-relay files from main.
func RegisterQrRelayScriptFS(bundle fs.FS) {
	qrRelayScriptFS = bundle
}

var qrRelayScriptFiles = []struct {
	embedPath string
	zipName   string
}{
	{"scripts/qr-relay/qr_relay.py", "qr-relay/qr_relay.py"},
	{"scripts/qr-relay/requirements.txt", "qr-relay/requirements.txt"},
	{"scripts/qr-relay/README.md", "qr-relay/README.md"},
	{"scripts/qr-relay/config.example.yaml", "qr-relay/config.example.yaml"},
}

// DownloadQrRelayScript serves a zip of the local capture script (JWT required).
// Optional ?relay_id= pre-fills config.yaml with platform URL / public path.
func DownloadQrRelayScript(c *gin.Context) {
	if _, ok := currentUserOrAbort(c); !ok {
		return
	}
	if qrRelayScriptFS == nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "QR relay script bundle is not available"})
		return
	}

	platformURL := strings.TrimRight(EffectivePublicBaseURL(), "/")
	if platformURL == "" {
		// Fall back to the URL the operator is currently using.
		scheme := "http"
		if c.Request.TLS != nil || strings.EqualFold(c.GetHeader("X-Forwarded-Proto"), "https") {
			scheme = "https"
		}
		host := c.Request.Host
		if host != "" {
			platformURL = scheme + "://" + host
		}
	}

	uploadToken := ""
	publicPath := ""
	relayName := ""
	if rawID := strings.TrimSpace(c.Query("relay_id")); rawID != "" {
		user, ok := currentUserOrAbort(c)
		if !ok {
			return
		}
		id, err := strconv.ParseUint(rawID, 10, 64)
		if err != nil || id == 0 {
			c.JSON(http.StatusBadRequest, gin.H{"error": "Invalid relay id"})
			return
		}
		var row models.QrRelay
		if err := config.GetDB().First(&row, id).Error; err != nil {
			c.JSON(http.StatusNotFound, gin.H{"error": "QR relay not found"})
			return
		}
		if !canAccessOwned(user, row.CreatedBy) {
			c.JSON(http.StatusForbidden, gin.H{"error": "Access denied"})
			return
		}
		publicPath = utils.QRRelayPublicPath(row.Slug)
		relayName = row.Name
		// Token is never stored in plaintext; leave placeholder.
		uploadToken = "PASTE_UPLOAD_TOKEN_FROM_CONSOLE"
	}

	configYAML := buildQrRelayConfigYAML(platformURL, uploadToken, publicPath, relayName)

	var buf bytes.Buffer
	zw := zip.NewWriter(&buf)
	for _, f := range qrRelayScriptFiles {
		data, err := fs.ReadFile(qrRelayScriptFS, f.embedPath)
		if err != nil {
			_ = zw.Close()
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to read embedded script: " + f.embedPath})
			return
		}
		w, err := zw.Create(f.zipName)
		if err != nil {
			_ = zw.Close()
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to build zip"})
			return
		}
		if _, err := w.Write(data); err != nil {
			_ = zw.Close()
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to write zip entry"})
			return
		}
	}
	// Always include a ready-to-edit config.yaml
	cw, err := zw.Create("qr-relay/config.yaml")
	if err != nil {
		_ = zw.Close()
		c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to build zip"})
		return
	}
	if _, err := cw.Write([]byte(configYAML)); err != nil {
		_ = zw.Close()
		c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to write config"})
		return
	}
	if err := zw.Close(); err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to finalize zip"})
		return
	}

	filename := fmt.Sprintf("fishing-qr-relay-%s.zip", time.Now().Format("20060102"))
	c.Header("Content-Type", "application/zip")
	c.Header("Content-Disposition", `attachment; filename="`+filename+`"`)
	c.Header("Cache-Control", "no-store")
	c.Data(http.StatusOK, "application/zip", buf.Bytes())
}

func buildQrRelayConfigYAML(platformURL, uploadToken, publicPath, relayName string) string {
	if uploadToken == "" {
		uploadToken = "PASTE_UPLOAD_TOKEN_FROM_CONSOLE"
	}
	if platformURL == "" {
		platformURL = "http://127.0.0.1:8000"
	}
	var b strings.Builder
	b.WriteString("# Generated by Fishing Platform — QR screen relay\n")
	if relayName != "" {
		b.WriteString("# Relay: " + relayName + "\n")
	}
	if publicPath != "" {
		b.WriteString("# Public image URL path: " + publicPath + "\n")
	}
	b.WriteString("# Upload API accepts image files only (multipart field \"image\").\n")
	b.WriteString("platform_url: " + yamlQuote(platformURL) + "\n")
	b.WriteString("upload_token: " + yamlQuote(uploadToken) + "\n")
	b.WriteString("\n")
	b.WriteString("interval_ms: 500\n")
	b.WriteString("heartbeat_interval_ms: 3000\n")
	b.WriteString("dedupe: true\n")
	b.WriteString("verify_tls: true\n")
	b.WriteString("\n")
	b.WriteString("# Optional capture region (pixels). Comment out for full primary monitor.\n")
	b.WriteString("# Or run: python qr_relay.py --pick-region -c config.yaml\n")
	b.WriteString("# region:\n")
	b.WriteString("#   left: 100\n")
	b.WriteString("#   top: 100\n")
	b.WriteString("#   width: 400\n")
	b.WriteString("#   height: 400\n")
	return b.String()
}

func yamlQuote(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	return `"` + s + `"`
}
